### ISSUE TITLE
Stl files not showing

### ISSUE THREAD

**Issue by dzach** [garyhodgson/githubiverse-template#2]
I like this idea very much and I'm trying to implement it in a small project that has a couple of test stl files. One problem I have is the stl files cannot be displayed on my githubverse page, although the bed grid does display correctly (you can see the page [here](http://dzach.github.com/3d_extruder_test/))

**Comment by garyhodgson** [comment]
There seems to be a problem with the Thingiview renderer, but when I try and load your stl file locally in thingiview direct then it works.  I'll have a look further tomorrow.

**Comment by garyhodgson** [comment]
Ok, I just realised the problem. The STL file is in binary format, and because I use the loadSTLString method to load the file in thingiview it doesn't work.  I'll try and think of a solution tomorrow, in the mean time if you want to get it looking nice you could try generating the stl files as ascii.

**Comment by dzach** [comment]
Thanks! Will try it.

**Comment by dzach** [comment]
Converted the stl files to ascii and they now show properly.
